Repository clubgamma/Air-Quality-Index-Analysis, pull requests merged in 2024-10, with the labels that each got.

#6 Minor Changes
  data/cleaned_delhi_air_quality_data.csv
Labels: good first issue, level 1, hacktoberfest-accepted

#7 Normalized Data
  data/aqi_scaled.csv
  notebooks/Data normalisation.ipynb
Labels: enhancement, level 2

#14 models notebook added
  notebooks/models.ipynb
Labels: level 1

#13 AQI for Indian states and Cities
  data/22CE079_AQI_Dataset.csv
  notebooks/22CE079_AQI.ipynb
Labels: enhancement, level 3

#12 Use Random Forest
  notebooks/aqi-pred_RandomForest.ipynb
Labels: enhancement, level 3

#11 Average AQI
  notebooks/notebooks.txt
Labels: level 2

#17 Gradient Boost Implementation
  notebooks/AirQualityIndex_GB.ipynb
Labels: enhancement, level 3

#16 New branch
  data/citywiseAQI_Index.csv
  notebooks/Average_AQI_by_city.ipynb
Labels: level 2

#15 Data Processing and PM2.5 Prediction Using XGBoost Regression
  data/AQI Data Set Hydrabad 22CE025.csv
  data/NEW_AQI_clean_dataset_hydrabad 22CE025.csv
  notebooks/22CE025_AQI_Levels_hydrabad_data_preprocessing.ipynb
  notebooks/22CE025_Model_training_Hydrabad_dataset.ipynb
  notebooks/22CE025_dataprocessing_&model_training.ipynb
Labels: enhancement, level 3, hacktoberfest-accepted

#18 implement #4: Handle Class Imbalance Using SMOTE
  data/sample_aqi_data.csv
  notebooks/aqi_prediction.ipynb
  src/data_prosessing.py
  src/model_training.py
Labels: level 2
